import type { BloggerAstDocument,BloggerAstNode,BloggerStructuralItem,BloggerXmlError,XmlMutation } from "@/types";
const attrs=(raw:string)=>{const out:Record<string,string>={};const re=/([^\s=/>]+)\s*=\s*(?:"([^"]*)"|'([^']*)')/g;let m:RegExpExecArray|null;while((m=re.exec(raw)))out[m[1]]=m[2]??m[3]??"";return out;};
const pos=(s:string,i:number)=>{const a=s.slice(0,i).split("\n");return{line:a.length,column:(a.at(-1)?.length??0)+1};};
const id=(i:number,n:string)=>`xml-${i}-${n.replace(/[^\w:-]/g,"-")}`;
function scan(source:string){const errors:BloggerXmlError[]=[];const root:BloggerAstNode={id:"root",type:"element",name:"#document",attributes:{},children:[],parentId:null,depth:0,start:0,end:source.length};const stack=[root];const re=/<!--[\s\S]*?-->|<\?[^?]*\?>|<[^>]+>|[^<]+/g;let m:RegExpExecArray|null;
while((m=re.exec(source))){const t=m[0],start=m.index,end=start+t.length;if(t.startsWith("<!--")){const p=stack.at(-1)!;p.children.push({id:id(start,"comment"),type:"comment",name:"#comment",attributes:{},children:[],text:t.slice(4,-3),parentId:p.id,depth:p.depth+1,start,end});continue;}if(t.startsWith("<?"))continue;if(!t.startsWith("<")){if(!t.trim())continue;const p=stack.at(-1)!;p.children.push({id:id(start,"text"),type:"text",name:"#text",attributes:{},children:[],text:t,parentId:p.id,depth:p.depth+1,start,end});continue;}if(/^<\s*\//.test(t)){const n=t.replace(/^<\s*\/\s*|\s*>$/g,"").trim(),c=stack.at(-1);if(!c||c.name!==n){const q=pos(source,start);errors.push({message:`وسم الإغلاق </${n}> لا يطابق البنية الحالية.`,line:q.line,column:q.column,index:start,severity:"error"});continue;}c.end=end;stack.pop();continue;}const self=/\/\s*>$/.test(t),open=t.replace(/^<\s*|\/?>$/g,"").trim(),nm=open.match(/^([^\s/>]+)/)?.[1];if(!nm)continue;const p=stack.at(-1)!;const node:BloggerAstNode={id:id(start,nm),type:"element",name:nm,attributes:attrs(open.slice(nm.length)),children:[],parentId:p.id,depth:p.depth+1,start,end};p.children.push(node);if(!self)stack.push(node);}
while(stack.length>1){const n=stack.pop()!;const q=pos(source,n.start);errors.push({message:`الوسم <${n.name}> غير مغلق.`,line:q.line,column:q.column,index:n.start,severity:"error"});}return{root,errors};}
export function parseBloggerXml(source:string):BloggerAstDocument{const r=scan(source);return{root:r.root,source,errors:r.errors};}
export function validateBloggerXml(source:string){return parseBloggerXml(source).errors;}
export function collectBloggerStructure(doc:BloggerAstDocument):BloggerStructuralItem[]{const out:BloggerStructuralItem[]=[];const visit=(n:BloggerAstNode)=>{if(n.type==="element"&&n.name!=="#document"){const x=n.name.toLowerCase();out.push({id:n.id,tag:n.name,type:x==="b:section"?"section":x==="b:widget"?"widget":x==="b:includable"?"includable":x==="b:skin"||x==="b:template-skin"?"skin":"element",attributes:{...n.attributes},depth:n.depth,parentId:n.parentId,start:n.start,end:n.end});}n.children.forEach(visit);};visit(doc.root);return out;}
const find=(n:BloggerAstNode,i:string):BloggerAstNode|null=>n.id===i?n:n.children.reduce<BloggerAstNode|null>((a,c)=>a??find(c,i),null);
const esc=(v:string)=>v.replace(/&/g,"&amp;").replace(/"/g,"&quot;");
const serialize=(n:BloggerAstNode):string=>n.type==="text"?n.text??"":n.type==="comment"?`<!--${n.text??""}-->`:n.name==="#document"?n.children.map(serialize).join(""):`<${n.name}${Object.entries(n.attributes).map(([k,v])=>` ${k}="${esc(v)}"`).join("")}>${n.children.map(serialize).join("")}</${n.name}>`;
export function beautifyBloggerXml(source:string,indent="  "){const d=parseBloggerXml(source);const render=(n:BloggerAstNode,depth:number):string=>{if(n.type==="text")return n.text?.trim()?indent.repeat(depth)+n.text.trim():"";if(n.type==="comment")return indent.repeat(depth)+`<!--${n.text??""}-->`;if(n.name==="#document")return n.children.map(c=>render(c,0)).filter(Boolean).join("\n");const a=Object.entries(n.attributes).map(([k,v])=>` ${k}="${esc(v)}"`).join(""),children=n.children.map(c=>render(c,depth+1)).filter(Boolean);return children.length?[indent.repeat(depth)+`<${n.name}${a}>`,...children,indent.repeat(depth)+`</${n.name}>`].join("\n"):indent.repeat(depth)+`<${n.name}${a}></${n.name}>`;};return render(d.root,0)+"\n";}
export function updateBloggerNode(source:string,m:XmlMutation){const d=parseBloggerXml(source),n=find(d.root,m.nodeId);if(!n)throw new Error("العنصر المطلوب غير موجود.");if(m.replaceWith!==undefined)return source.slice(0,n.start)+m.replaceWith+source.slice(n.end);if(m.deleteNode){const walk=(p:BloggerAstNode):boolean=>{const i=p.children.findIndex(c=>c.id===m.nodeId);if(i>=0){p.children.splice(i,1);return true;}return p.children.some(c=>c.type==="element"&&walk(c));};if(!walk(d.root))throw new Error("تعذر حذف العنصر.");return serialize(d.root);}if(m.attribute){if(m.value===undefined)throw new Error("قيمة الخاصية مطلوبة.");n.attributes[m.attribute]=m.value;}return serialize(d.root);}
export function insertBloggerNode(source:string,parentId:string,markup:string){const d=parseBloggerXml(source),p=find(d.root,parentId),f=parseBloggerXml(markup);if(!p||p.type!=="element")throw new Error("العنصر الأب غير موجود.");if(f.errors.length)throw new Error("الوسم الجديد غير صالح.");p.children.push(...f.root.children);return serialize(d.root);}
